language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: CEzZ6liaZlR6b2vIHWLKcrDuCgGjdyakzDo38VPnqKIMckYLtuaPNBmHKY6fNYuEHrUEj6nS5DgJL1EJHuNjnw25imSKnTudIW5kzWo/b+rUoHs3u2Ju6lvFCJ8ktvENlDolv7C1ICIu7efPpz/m0YG5miCVEDMOks4yFwL4Rpicut7zzcDMs24YqQQ/EsC+cKoLSdVXG9lBcNdR6tKbGPFOGBdUYL6uaP3oBWlUARrZX2ytehz7xjHScDkZekhD/uIOzCtuVbRNMVnmuyCmjt1PoUSuACdFhkKlVlVG/Z9wd5Ygkx72imoRK7vwc8GfqJtuhDUp3LJovD0zuJmlgeoIoe6s0lJtBgZy+2pcEBnc7dWmWIm8hnXM44pZQbwOssjiYJxiQkUvt2yngM1rKuZrSkVlQw4JHyHqp3ASZ3EWO6jBllENY2ZMCQ+s5EYoGAuHTrJ6f3o3H/je67anI6FR8YDE2rjiYJqrsot9fM43bDz3i1rbgs028GsDHcbXLyZ7/K9YpA8dybKMmEOLN0ejUQNISlkMXLlLLUOqcBFg5YeAgsR5wI3juSzY3JL1686Qh9FOYeZVCZi/ZbcMXJ9Z3N2a3DQS6XMIPi9geoPkgYhNUMrlXAzYPNU0FsIjDEM5xUb/pK9MPs8fgyz3dCCor9yAYvqJ6oxu/s3OK60=
  app: dibs-app
  on:
    repo: mike-crane/dibs-client
