language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: vxP5f1UZnXzj75K6QL85a36PUQKzR+jIkPTlo4jwUiPExztlbTPmpNhDSJBvBjAx/uGYLM50sV41bcmOBoX5ldGR4Sai+9DqrEmEsLYHIFcyNrjLVbmZvxOiw/5QRyxEgjicc/SynrfJpdt5Umvn5LYNDzkcf4Ky/kwoBOE9N6SmnqbxWazvvlRNS8SNDzugaL1WqM267RoUQBYDnMT1vUjIRAVCoJAZo9UYmJ5giOKRrGgrmQIFDzkXkfk1brzbYl2k314fk9bjnOvgVU/ZAtnYrZnifw8I0sBL+/Y5I2MbmE/3b1Z+GjltzgX1ifJCieS2SU/YazezEgcwDCWFqqPOfNcTyC8Bn8/4aPJsA3hBnovsc5zjmWUMVkx5SRyvxtJGBsZSQXtUZLVIFr2ewQd9sW7kJ2c4HyOZq7OqlvLE1VxC3T05tYZsJa5R9qlLV1ymQhV81WHyr/aS9/fGSJUjf7zyinm5MimWJRWdiiW5iBx9W8fjGkSUvsYt6mEgDbZPBXWfNfzSw6PDhWpLQBPV5bMBzIBniiaGBk+lPHaGH5rLjormCpkKu/+s+GxYEZxmwVmISULQEJ1LK+SCVmKpKoJsRC4JQzAQ7jSie34oLbWHnpOQ9W1Klnm3r3IePTkLEIFhARA7EJSJfCGKHFesXl/iEHy7tFBF1+N0ujo=
  app: dibs-app
  on:
    repo: mike-crane/dibs-client
